services:
  # Backend Web Service
  - type: web
    name: task-management-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
      - key: INIT_DB
        value: true
    
  # Frontend Static Site  
  - type: web
    name: task-management-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: task-management-backend
          property: host

  # PostgreSQL Database
  - type: pgsql
    name: task-management-db
    databaseName: taskmanagement
    user: taskuser