services:
  # Backend Web Service
  - type: web
    name: task-management-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python -c "from app import create_app; from app import db; from app.models.task import Task; from app.models.comment import Comment; app = create_app(); app.app_context().push(); db.create_all(); print('Database initialized')"
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
    
  # Frontend Static Site  
  - type: web
    name: task-management-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: task-management-backend
          property: host
    user: taskuser